### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by soroush-bn** [soroush-bn/noraxon-sensor#7]
- [ ] putting results into latex

- [ ] comparing results
- [ ] checking filters
- [ ] finding activate threshold
- [ ] correcting metrics for IMU

- [ ] SFFS
